version: '3'

services:
  react-app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: react-img-prod:latest
    container_name: react-container-prod
    ports:
      - 80:8080 # localport:dockerport
