# for devcontainer
version: '3'

services:
  react-app:
    build:
      target: devcontainer
      context: ./
      dockerfile: Dockerfile
    image: react-img-devcontainer:latest
    container_name: react-container-devcontainer
    volumes:
      - ./:/app
